# Loading sector data

## Imports

In [2]:
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import scipy.cluster.hierarchy as sch
from scipy.cluster.hierarchy import dendrogram, linkage
from scipy import stats
from scipy.stats import norm
import requests
import os
import plotly.graph_objects as go
import dataframe_image as dfi
import time
from bs4 import BeautifulSoup # library to parse HTML documents
from collections import Counter
import re
import pyfolio as pf
import itertools
from itertools import chain
import matplotlib_venn
import matplotlib.ticker as mtick
from matplotlib_venn import venn3
import networkx as nx
from upsetplot import from_contents
from upsetplot import plot
import matplotlib.patches as mpatches
import matplotlib.dates as mdates
import matplotlib.lines as mlines
from matplotlib.dates import DateFormatter, DayLocator
import imgkit
%matplotlib inline

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyfolio/pos.py:26: UserWarning: Module "zipline.assets" not found; mutltipliers will not be applied to position notionals.
  warnings.warn(

In [65]:
def create_dfs(read_path, write_path, n_remove_rows):
    df = pd.read_csv(read_path)
    df = df.drop(df.index[:n_remove_rows])
    df = df[['Ticker', 'Name', 'Sector', 'Industry']]
    df = df.rename({'Ticker': 'date', 'Name': 'ticker', 'Sector': 'close', 'Industry': 'marketcap'}, axis=1)

    reshaped_df = df.pivot(index='date', columns='ticker', values='close')
    reshaped_df = reshaped_df.reset_index()

    reshaped_df.to_csv(write_path)

In [66]:
create_dfs('finaeon_dfs/df_consumer_discretionary.csv', 'sector_dfs/consumer_discreationary.csv', 50)

/var/folders/5j/dtbtysr93p94g67dwcq9gx9m0000gn/T/ipykernel_84358/3250515836.py:2: DtypeWarning: Columns (2,3,4,5,6,8,10,11,12,13,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(read_path)

In [67]:
create_dfs('finaeon_dfs/df_consumer_staples.csv', 'sector_dfs/consumer_staples.csv', 34)

/var/folders/5j/dtbtysr93p94g67dwcq9gx9m0000gn/T/ipykernel_84358/3250515836.py:2: DtypeWarning: Columns (2,3,4,5,6,8,10,11,12,13,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(read_path)

In [69]:
create_dfs('finaeon_dfs/df_energy.csv', 'sector_dfs/energy.csv', 22)

In [70]:
create_dfs('finaeon_dfs/df_financials.csv', 'sector_dfs/financials.csv', 52)

/var/folders/5j/dtbtysr93p94g67dwcq9gx9m0000gn/T/ipykernel_84358/3250515836.py:2: DtypeWarning: Columns (2,3,4,5,6,8,10,11,12,13,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(read_path)

In [71]:
create_dfs('finaeon_dfs/df_health_care.csv', 'sector_dfs/health_care.csv', 52)

/var/folders/5j/dtbtysr93p94g67dwcq9gx9m0000gn/T/ipykernel_84358/3250515836.py:2: DtypeWarning: Columns (2,3,4,5,6,8,10,11,12,13,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(read_path)

In [72]:
create_dfs('finaeon_dfs/df_industrials.csv', 'sector_dfs/industrials.csv', 62)

/var/folders/5j/dtbtysr93p94g67dwcq9gx9m0000gn/T/ipykernel_84358/3250515836.py:2: DtypeWarning: Columns (2,3,4,5,6,8,10,11,12,13,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(read_path)

In [74]:
create_dfs('finaeon_dfs/df_information_technology.csv', 'sector_dfs/information_technology.csv', 68)

/var/folders/5j/dtbtysr93p94g67dwcq9gx9m0000gn/T/ipykernel_84358/3250515836.py:2: DtypeWarning: Columns (2,3,4,5,6,8,10,11,12,13,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(read_path)

In [75]:
create_dfs('finaeon_dfs/df_materials.csv', 'sector_dfs/materials.csv', 25)

/var/folders/5j/dtbtysr93p94g67dwcq9gx9m0000gn/T/ipykernel_84358/3250515836.py:2: DtypeWarning: Columns (2,3,4,5,6,8,10,11,12,13,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(read_path)

In [76]:
create_dfs('finaeon_dfs/df_real_estate.csv', 'sector_dfs/real_estate.csv', 12)

In [77]:
create_dfs('finaeon_dfs/df_telecommunication_services.csv', 'sector_dfs/communication_services.csv', 6)

In [80]:
create_dfs('finaeon_dfs/df_utilities.csv', 'sector_dfs/utilities.csv', 32)

/var/folders/5j/dtbtysr93p94g67dwcq9gx9m0000gn/T/ipykernel_84358/3250515836.py:2: DtypeWarning: Columns (2,3,4,5,6,8,10,11,12,13,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(read_path)

In [82]:
df = pd.read_csv('finaeon_dfs/df_telecommunication_services.csv')
df.head(20)

,Ticker,Name,Series Type,Currency,Country,Sector,Industry,Sic,Exchange,Cik,Fiscal_End,Units,Scale,Flow,Adjustment,Periodicity,Metadata,Corporate_History,Data Notes
0,VZ,Verizon Communications (Bell Atlantic Corp.),Securities - Current,United States Dollar,United States,Utilities & Telecommunications,Telephone,4813.0,"Consolidated Issue, listed by NYSE",732712.0,12/31,National Currency,Units,Stock,none,Daily From Nov 1983 To Dec 2023<BR>,"Provides communications services, including lo...",Bell Atlantic Corp. incorporated in DE on Octo...,Split adjusted.
1,T,AT&T Inc. (Southwestern Bell - SBC Corp.),Securities - Current,United States Dollar,United States,Utilities & Telecommunications,Telephone,4813.0,"Consolidated Issue, listed by NYSE",732717.0,12/31,National Currency,Units,Stock,none,Daily From Nov 1983 To Dec 2023<BR>,Provides communications products and services ...,Southwestern Bell Corp. changed its name to SB...,Split adjusted.
2,AMT,"American Tower Corp., Class A",Securities - Current,United States Dollar,United States,Utilities & Telecommunications,Telephone,4899.0,"Consolidated Issue, listed by NYSE",1053507.0,12/31,National Currency,Units,Stock,none,Daily From Feb 1998 To Dec 2023<BR>,American Tower Corp. is a holding company that...,American Tower Systems Corp. incorporated on J...,Split adjusted.
3,CCI,Crown Castle Inc,Securities - Current,United States Dollar,United States,Utilities & Telecommunications,Telephone,4899.0,New York Stock Exchange,1051470.0,12/31,National Currency,Units,Stock,none,Daily From Aug 1998 To Dec 2023<BR>,"Crown Castle International owns, operates and ...",Crown Castle International Corp incorporated i...,Split adjusted.
4,TMUS,T-Mobile US Inc,Securities - Current,United States Dollar,United States,Utilities & Telecommunications,Telephone,4812.0,Over-the-Counter,1283699.0,12/31,National Currency,Units,Stock,none,Daily From Apr 2007 To Dec 2023<BR>,"MetroPCS Communications, Inc., a wireless tele...",MetroPCS Communications Inc. incorporated in D...,Split adjusted.
5,Date,Ticker,Open,High,Low,Close,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,01/02/2018,AMT,143.16,143.22,140.91,141.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,01/03/2018,AMT,141.05,142.5,140.86,141.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,01/04/2018,AMT,141.44,141.96,139.58,139.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,01/05/2018,AMT,140.23,140.7,139.59,140.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,01/08/2018,AMT,140.66,143.24,140.66,142.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,01/09/2018,AMT,142.1,142.25,140.86,141.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,01/10/2018,AMT,140.41,140.6,136.03,137.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,01/11/2018,AMT,138,138.01,134.51,134.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,01/12/2018,AMT,135.39,135.5,132.54,133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,01/16/2018,AMT,133.24,138,133.24,135.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,01/17/2018,AMT,136.12,137.16,135.55,136.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,01/18/2018,AMT,136.58,136.67,134.72,135.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,01/19/2018,AMT,135.9,137.68,134.75,137.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,01/22/2018,AMT,137.69,139.24,137.41,139.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
df = df.drop(df.index[:32])
df = df[['Ticker', 'Name', 'Sector', 'Industry']]
df

          Ticker Name  Sector Industry
32    02/08/2018  AMT  133.57      NaN
33    02/09/2018  AMT  136.05      NaN
34    02/12/2018  AMT  136.23      NaN
35    02/13/2018  AMT  136.31      NaN
36    02/14/2018  AMT  135.48      NaN
...          ...  ...     ...      ...
7484  12/05/2023   VZ   38.42      NaN
7485  12/06/2023   VZ    38.5      NaN
7486  12/07/2023   VZ   38.65      NaN
7487  12/08/2023   VZ   38.25      NaN
7488  12/11/2023   VZ   37.67      NaN

[7457 rows x 4 columns]

In [84]:
df = df.rename({'Ticker': 'time', 'Name': 'ticker', 'Sector': 'close', 'Industry': 'marketcap'}, axis=1)
df

            time ticker   close marketcap
32    02/08/2018    AMT  133.57       NaN
33    02/09/2018    AMT  136.05       NaN
34    02/12/2018    AMT  136.23       NaN
35    02/13/2018    AMT  136.31       NaN
36    02/14/2018    AMT  135.48       NaN
...          ...    ...     ...       ...
7484  12/05/2023     VZ   38.42       NaN
7485  12/06/2023     VZ    38.5       NaN
7486  12/07/2023     VZ   38.65       NaN
7487  12/08/2023     VZ   38.25       NaN
7488  12/11/2023     VZ   37.67       NaN

[7457 rows x 4 columns]

In [85]:
reshaped_df = df.pivot(index='time', columns='ticker', values='close')
reshaped_df = reshaped_df.reset_index()
# reshaped_df = reshaped_df.drop(columns=['Ticker'])

reshaped_df.head(20)

ticker        time     AMT     CCI                 T    TMUS     VZ
0       01/02/2018     NaN  108.93  5.40051230599353   64.04  53.53
1       01/02/2019  156.74  105.95   4.1393651665555   65.26  56.02
2       01/02/2020   228.5  141.68  5.44535309317355   78.59  61.05
3       01/03/2018     NaN  108.47   5.2757988666491   63.61  52.43
4       01/03/2019  157.68  106.48    4.144970264953   65.02  56.22
5       01/03/2020  228.61  142.46  5.47337858516106   78.17   60.4
6       01/03/2022  286.38  207.74  3.56344130621213  114.43  52.44
7       01/03/2023  214.67  138.31             18.74  139.04  40.12
8       01/04/2018     NaN  107.21  5.32484347762725      63   52.6
9       01/04/2019  158.31  108.07  4.25146713450555   67.49  56.36
10      01/04/2021   219.6     155  4.12535242056174  132.43  58.85
11      01/04/2022  282.77  202.15  3.59286807279902  114.06  53.47
12      01/04/2023     219  143.35             19.14  139.96  41.13
13      01/05/2018     NaN  108.03  5.34446132201851    64.6  52.48
14      01/05/2021  220.71  155.61  4.10012947777298  131.85  58.58
15      01/05/2022  264.57  188.46  3.67274072496343  115.36  54.02
16      01/05/2023  212.13  140.75             19.21  144.48   41.7
17      01/06/2020  228.55  141.26  5.47898368355856   78.62  60.27
18      01/06/2021  214.89  151.43  4.18000212993739  131.53  59.29
19      01/06/2022  264.89   192.5  3.65872797896967  115.57  53.76

## Check with yahoo finance