# Module for loading all the data of the indices

## Imports

In [1]:
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import scipy.cluster.hierarchy as sch
from scipy.cluster.hierarchy import dendrogram, linkage
from scipy import stats
from scipy.stats import norm
import requests
import os
import plotly.graph_objects as go
import dataframe_image as dfi
import time
from bs4 import BeautifulSoup # library to parse HTML documents
from collections import Counter
import re
import pyfolio as pf
import itertools
from itertools import chain
import matplotlib_venn
import matplotlib.ticker as mtick
from matplotlib_venn import venn3
import networkx as nx
from upsetplot import from_contents
from upsetplot import plot
import matplotlib.patches as mpatches
import matplotlib.dates as mdates
import matplotlib.lines as mlines
from matplotlib.dates import DateFormatter, DayLocator
import imgkit
%matplotlib inline

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyfolio/pos.py:26: UserWarning: Module "zipline.assets" not found; mutltipliers will not be applied to position notionals.
  warnings.warn(

In [2]:
import cvxpy as cp
from pypfopt.efficient_frontier import EfficientFrontier
from pypfopt import risk_models
from pypfopt import expected_returns

(CVXPY) Nov 30 03:17:10 PM: Encountered unexpected exception importing solver CBC:
ImportError("dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cylp/cy/CyCoinIndexedVector.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__ZN9CoinError12printErrors_E'")

In [3]:
import cylp

In [29]:
from pandas_datareader import data
import openai

## Load all tickers (SP500, NASDAQ, Dow Jones)

In [14]:
# get the response in the form of html
wikiurl="https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
#table_class="wikitable sortable components"
response=requests.get(wikiurl)
print(response.status_code)

200

In [15]:
# parse data from the html into a beautifulsoup object
soup = BeautifulSoup(response.text, 'html.parser')
indiatable=soup.find_all('table',{'class':"wikitable"})

In [16]:
df_sp500 = pd.read_html(str(indiatable[0]))
# convert list to dataframe
df_sp500=pd.DataFrame(df_sp500[0])
print(df_sp500.head())

  Symbol     Security             GICS Sector               GICS Sub-Industry
0    MMM           3M             Industrials        Industrial Conglomerates  \
1    AOS  A. O. Smith             Industrials               Building Products
2    ABT       Abbott             Health Care           Health Care Equipment
3   ABBV       AbbVie             Health Care                 Pharmaceuticals
4    ACN    Accenture  Information Technology  IT Consulting & Other Services

     Headquarters Location  Date added      CIK      Founded
0    Saint Paul, Minnesota  1957-03-04    66740         1902
1     Milwaukee, Wisconsin  2017-07-26    91142         1916
2  North Chicago, Illinois  1957-03-04     1800         1888
3  North Chicago, Illinois  2012-12-31  1551152  2013 (1888)
4          Dublin, Ireland  2011-07-06  1467373         1989

In [17]:
df_sp500

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
499,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
500,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
501,ZION,Zions Bancorporation,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [18]:
test = ['XOM', 'CVX', 'COP', 'SLB', 'EOG', 'PSX', 'KMI', 'OXY', 'VLO', 'WMB', 'HAL', 'MPC', 'NOV', 'BKR', 'DVN']

In [28]:
for t in test:
    a = df_sp500[df_sp500['Symbol'] == t]
    if a.empty:
        print(f'{t} NOT in SP500')
    else:
        print(f'{t} in SP500')
        # print(a['Symbol'])

XOM in SP500
CVX in SP500
COP in SP500
SLB in SP500
EOG in SP500
PSX in SP500
KMI in SP500
OXY in SP500
VLO in SP500
WMB in SP500
HAL in SP500
MPC in SP500
NOV NOT in SP500
BKR in SP500
DVN in SP500

In [4]:
## In-sample end date (using 5 years of weekly data prior to end date)
insample_enddate = datetime(2021, 8, 31)

## Out-of-sample dates (using daily data)

# First out-of-sample period (1 Sept 2021 to 31 July 2023)
outsample_startdate1 = datetime(2021, 9, 1)
outsample_enddate1   = datetime(2023, 7,  31)

# Second out-of-sample period (14 March 2023 to 31 July 2023) (choose one out of the two at a time)
# outsample_startdate2 = datetime(2023, 5,  1)
outsample_startdate2 = datetime(2023, 3,  14)
outsample_enddate2   = datetime(2023, 7,  31)

In [5]:
insample_startdate = insample_enddate - timedelta(weeks=5*52) # five years prior to September 2021

In [13]:
panel_data = data.DataReader('SP500-10', 'google', insample_startdate, insample_enddate)

NotImplementedError: data_source='google' is not implemented

In [11]:
# Define the S&P500 ticker symbol
ixt_ticker = "^IXT"

# Getting S&P 500 data (in-sample)
ixt_ins = yf.download(ixt_ticker, start=insample_startdate, end=insample_enddate, interval='1wk', period='1d')
ixt_ins['SP_Return'] = ixt_ins['Adj Close'].pct_change()

# Drop NA values in S&P 500 return data
ixt_ins.dropna(subset=['SP_Return'], inplace=True) # 1256 X 7 (removed first row with NaN in return)

# Getting S&P 500 data (out-of-sample)
ixt_outs = yf.download(ixt_ticker, start=outsample_startdate1, end=outsample_enddate1)
ixt_outs['SP_Return'] = ixt_outs['Adj Close'].pct_change()

# Drop NA values in S&P 500 return data
ixt_outs.dropna(subset=['SP_Return'], inplace=True) # removed first row with NaN in return

[*********************100%***********************]  1 of 1 completed

1 Failed download:
['^IXT']: Exception('%ticker%: No price data found, symbol may be delisted (1wk 2016-09-06 00:00:00 -> 2021-08-31 00:00:00)')

[*********************100%***********************]  1 of 1 completed

1 Failed download:
['^IXT']: Exception("%ticker%: Period 'max' is invalid, must be one of ['1d', '5d']")

## Building 11 portfolios

In [30]:
#API Key

API_KEY= "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"


#The OpenAI Key
import os
os.environ['OPENAI_API_KEY'] =API_KEY
openai.api_key = os.getenv("OPENAI_API_KEY")

In [32]:
for elem in openai.Model.list()["data"]:
    print(elem['id'])

text-search-babbage-doc-001
curie-search-query
text-davinci-003
text-search-babbage-query-001
babbage
babbage-search-query
text-babbage-001
text-similarity-davinci-001
davinci-similarity
code-davinci-edit-001
curie-similarity
babbage-search-document
curie-instruct-beta
text-search-ada-doc-001
davinci-instruct-beta
text-similarity-babbage-001
text-search-davinci-doc-001
gpt-3.5-turbo-0613
babbage-similarity
text-embedding-ada-002
davinci-search-query
text-similarity-curie-001
text-davinci-001
text-search-davinci-query-001
gpt-3.5-turbo-16k-0613
ada-search-document
ada-code-search-code
babbage-002
davinci-002
gpt-3.5-turbo
davinci-search-document
curie-search-document
babbage-code-search-code
text-search-ada-query-001
code-search-ada-text-001
babbage-code-search-text
code-search-babbage-code-001
ada-search-query
ada-code-search-text
dall-e-3
tts-1-hd
text-search-curie-query-001
text-davinci-002
text-davinci-edit-001
code-search-babbage-text-001
ada
text-ada-001
ada-similarity
code-search-ada-code-001
gpt-3.5-turbo-instruct
text-similarity-ada-001
gpt-3.5-turbo-instruct-0914
canary-whisper
text-search-curie-doc-001
gpt-3.5-turbo-16k
text-curie-001
curie
canary-tts
tts-1
whisper-1
davinci
gpt-3.5-turbo-1106
dall-e-2
tts-1-1106
gpt-3.5-turbo-0301
tts-1-hd-1106

In [33]:
# OpenAI API parameters
model = "gpt-3.5-turbo-0613"
max_tokens = 1024
n = 1
stop = None
temperature = 0.5

In [34]:
sectors = ['Information_Technology', 'Health_Care', 'Financials', 'Consumer_Discretionary', \
           'Communication_Services', 'Industrials', 'Consumer_Staples', 'Energy',\
           'Utilities', 'Real_Estate', 'Materials']

In [36]:
def generate_stocks_by_sector(index, n_count, n_stocks, outperform_index=None, recount=False):

    if not outperform_index: outperform_index = index

    # Your CSV file path
    csv_path = f'sectors_new/stocks15_auto_{index}.csv'

    # Check if CSV file exists
    if os.path.isfile(csv_path) and not recount:
        # Read from CSV
        df = pd.read_csv(csv_path)
        print("Reading from local csv file")

        # Convert DataFrame columns to dictionary and list
        stock_counter = df.set_index('Stocks')['Count'].to_dict()
        valid_most_common_stocks = df.loc[df['IsValid'] == 1, 'Stocks'].tolist()
        
        print(stock_counter)
        print("The valid most common stocks are: ", valid_most_common_stocks)


    else:    
        # Generate first prompt
        prompt1 = f"Using a range of investing principles taken from leading funds, create a theoretical fund comprising of at least {n_stocks} stocks (mention their tickers) from the {index} index with the goal to outperform the {outperform_index} index"
 
        # Initialize dictionary to count stock occurrences
        stock_counter = Counter()

        # Initialize list to store the number of stocks in each iteration
        num_stocks_per_iter = []

        for i in range(n_count):
            # Call OpenAI API for the first response
            response1 = openai.ChatCompletion.create(
                model=model,
                messages=[
                {"role": "system", "content": "You are a helpful  assistant."},
                {"role": "user", "content": prompt1},
                ],
                max_tokens=max_tokens,
                n=n,
                stop=stop,
                temperature=temperature,
            )

            coutput1 = response1['choices'][0]['message']['content']

            # Generate second prompt
            prompt2 = 'Extract only the ticker symbols of the stocks comprising the fund from the previous response:- "{input}". In your response to this prompt, list only the ticker symbols separated by spaces.'.format(input=coutput1)

            # Call OpenAI API for the second response
            response2 = openai.ChatCompletion.create(
                model=model,
                messages=[
                {"role": "system", "content": "You are a helpful  assistant."},
                {"role": "user", "content": prompt2},
                ],
                max_tokens=max_tokens,
                n=n,
                stop=stop,
                temperature=temperature,
            )

            coutput2 = response2['choices'][0]['message']['content']

            # Get stock tickers as a list
            stock_tickers = coutput2.split()

            # Replace "." with "-"
            stock_tickers = [ticker.replace(".", "-") for ticker in stock_tickers]

            # Replace "FB" with "META"
            stock_tickers = ["META" if ticker == "FB" else ticker for ticker in stock_tickers]
            print(stock_tickers)

            num_stocks_per_iter.append(len(stock_tickers))
            print(num_stocks_per_iter)

            # Update the stock occurrences counter
            stock_counter.update(stock_tickers)
            print(stock_counter)

        # Calculate average and round to nearest integer
        average = round(np.mean(num_stocks_per_iter))

        # Get a list of all the stocks, sorted by frequency (from most to least common)
        sorted_stocks = [stock for stock, _ in stock_counter.most_common()]

        # Assuming that tickers_sp500 is your numpy array of valid S&P 500 stock tickers
        # valid_tickers = set(tickers_sp500)  # Convert to a set for faster membership checking

        # # Initialize list to store valid most common stocks
        valid_most_common_stocks = []

        # # Iterate over the sorted stocks
        for stock in sorted_stocks:
            # If the stock is valid and we still need more stocks to reach the number 15
            if len(valid_most_common_stocks) < 15:
                valid_most_common_stocks.append(stock)
            # elif stock not in valid_tickers:
            #     print(f"The stock {stock} is not in the valid list of S&P 500 and hence is being discarded.")

        # Check if we have enough valid stocks
        # if len(valid_most_common_stocks) < 15:
        #     print("There are not enough valid stocks to reach the desired number of 15 stocks.")

        print("The valid most common stocks are: ", valid_most_common_stocks)
        
        # Convert stock_counter to DataFrame and add valid_most_common_stocks as a new column
        df = pd.DataFrame.from_dict(stock_counter, orient='index', columns=['Count']).reset_index().rename(columns={'index': 'Stocks'})
        df['IsValid'] = df['Stocks'].apply(lambda x: 1 if x in valid_most_common_stocks else 0)

        # Save to CSV
        df.to_csv(csv_path, index=False)

In [45]:
def check_if_stock_in_sp500(stock_list):
    for stock in stock_list:
        temp = df_sp500[df_sp500['Symbol'] == stock]
        if temp.empty:
            print(f'{stock} NOT in SP500')
        else:
            print(f'{stock} in SP500')

## Energy sector

In [37]:
generate_stocks_by_sector('S&P 500-10 energy', 3, 15)

['XOM', 'CVX', 'COP', 'SLB', 'PSX', 'EOG', 'KMI', 'OXY', 'VLO', 'MPC', 'WMB', 'HAL', 'BKR', 'PXD', 'DVN']
[15]
Counter({'XOM': 1, 'CVX': 1, 'COP': 1, 'SLB': 1, 'PSX': 1, 'EOG': 1, 'KMI': 1, 'OXY': 1, 'VLO': 1, 'MPC': 1, 'WMB': 1, 'HAL': 1, 'BKR': 1, 'PXD': 1, 'DVN': 1})
['XOM', 'CVX', 'COP', 'SLB', 'EOG', 'PXD', 'PSX', 'VLO', 'MPC', 'KMI', 'BKR', 'OXY', 'DVN', 'WMB', 'HAL']
[15, 15]
Counter({'XOM': 2, 'CVX': 2, 'COP': 2, 'SLB': 2, 'PSX': 2, 'EOG': 2, 'KMI': 2, 'OXY': 2, 'VLO': 2, 'MPC': 2, 'WMB': 2, 'HAL': 2, 'BKR': 2, 'PXD': 2, 'DVN': 2})
['XOM', 'CVX', 'COP', 'SLB', 'PXD', 'EOG', 'PSX', 'KMI', 'BKR', 'VLO', 'MPC', 'OXY', 'NOV', 'HAL', 'WMB']
[15, 15, 15]
Counter({'XOM': 3, 'CVX': 3, 'COP': 3, 'SLB': 3, 'PSX': 3, 'EOG': 3, 'KMI': 3, 'OXY': 3, 'VLO': 3, 'MPC': 3, 'WMB': 3, 'HAL': 3, 'BKR': 3, 'PXD': 3, 'DVN': 2, 'NOV': 1})
The valid most common stocks are:  ['XOM', 'CVX', 'COP', 'SLB', 'PSX', 'EOG', 'KMI', 'OXY', 'VLO', 'MPC', 'WMB', 'HAL', 'BKR', 'PXD', 'DVN']

In [40]:
energy_stocks = list(pd.read_csv('sectors_new/stocks15_auto_S&P 500-10 energy.csv')['Stocks'].T)
energy_stocks

['XOM',
 'CVX',
 'COP',
 'SLB',
 'PSX',
 'EOG',
 'KMI',
 'OXY',
 'VLO',
 'MPC',
 'WMB',
 'HAL',
 'BKR',
 'PXD',
 'DVN',
 'NOV']

In [42]:
check_if_stock_in_sp500(energy_stocks)

XOM in SP500
CVX in SP500
COP in SP500
SLB in SP500
PSX in SP500
EOG in SP500
KMI in SP500
OXY in SP500
VLO in SP500
MPC in SP500
WMB in SP500
HAL in SP500
BKR in SP500
PXD in SP500
DVN in SP500
NOV NOT in SP500

## Materials sector

In [43]:
generate_stocks_by_sector('S&P 500-15 materials', 3, 15)

['APD', 'ALB', 'AVY', 'BLL', 'CF', 'DOW', 'DD', 'ECL', 'FCX', 'IP', 'LYB', 'MOS', 'NUE', 'SHW', 'WRK']
[15]
Counter({'APD': 1, 'ALB': 1, 'AVY': 1, 'BLL': 1, 'CF': 1, 'DOW': 1, 'DD': 1, 'ECL': 1, 'FCX': 1, 'IP': 1, 'LYB': 1, 'MOS': 1, 'NUE': 1, 'SHW': 1, 'WRK': 1})
['LIN', 'ECL', 'SHW', 'APD', 'DOW', 'PPG', 'PX', 'FCX', 'IP', 'NUE', 'WRK', 'LYB', 'ALB', 'NEM', 'MLM']
[15, 15]
Counter({'APD': 2, 'ALB': 2, 'DOW': 2, 'ECL': 2, 'FCX': 2, 'IP': 2, 'LYB': 2, 'NUE': 2, 'SHW': 2, 'WRK': 2, 'AVY': 1, 'BLL': 1, 'CF': 1, 'DD': 1, 'MOS': 1, 'LIN': 1, 'PPG': 1, 'PX': 1, 'NEM': 1, 'MLM': 1})
['LIN', 'ECL', 'APD', 'SHW', 'PPG', 'IP', 'DOW', 'LYB', 'WRK', 'NUE', 'FCX', 'VMC', 'NEM', 'BLL', 'MLM']
[15, 15, 15]
Counter({'APD': 3, 'DOW': 3, 'ECL': 3, 'FCX': 3, 'IP': 3, 'LYB': 3, 'NUE': 3, 'SHW': 3, 'WRK': 3, 'ALB': 2, 'BLL': 2, 'LIN': 2, 'PPG': 2, 'NEM': 2, 'MLM': 2, 'AVY': 1, 'CF': 1, 'DD': 1, 'MOS': 1, 'PX': 1, 'VMC': 1})
The valid most common stocks are:  ['APD', 'DOW', 'ECL', 'FCX', 'IP', 'LYB', 'NUE', 'SHW', 'WRK', 'ALB', 'BLL', 'LIN', 'PPG', 'NEM', 'MLM']

In [46]:
materials_stocks = list(pd.read_csv('sectors_new/stocks15_auto_S&P 500-15 materials.csv')['Stocks'].T)
materials_stocks

['APD',
 'ALB',
 'AVY',
 'BLL',
 'CF',
 'DOW',
 'DD',
 'ECL',
 'FCX',
 'IP',
 'LYB',
 'MOS',
 'NUE',
 'SHW',
 'WRK',
 'LIN',
 'PPG',
 'PX',
 'NEM',
 'MLM',
 'VMC']

In [47]:
check_if_stock_in_sp500(materials_stocks)

APD in SP500
ALB in SP500
AVY in SP500
BLL NOT in SP500
CF in SP500
DOW in SP500
DD in SP500
ECL in SP500
FCX in SP500
IP in SP500
LYB in SP500
MOS in SP500
NUE in SP500
SHW in SP500
WRK in SP500
LIN in SP500
PPG in SP500
PX NOT in SP500
NEM in SP500
MLM in SP500
VMC in SP500

## Industrials sector

In [48]:
generate_stocks_by_sector('S&P 500-20 industrials', 3, 15)

['HON', 'MMM', 'UTX', 'CAT', 'BA', 'UNP', 'GE', 'FDX', 'EMR', 'LMT', 'RTX', 'UPS', 'GD', 'ITW', 'NOC']
[15]
Counter({'HON': 1, 'MMM': 1, 'UTX': 1, 'CAT': 1, 'BA': 1, 'UNP': 1, 'GE': 1, 'FDX': 1, 'EMR': 1, 'LMT': 1, 'RTX': 1, 'UPS': 1, 'GD': 1, 'ITW': 1, 'NOC': 1})
['BA', 'HON', 'UTX', 'GE', 'CAT', 'MMM', 'UNP', 'FDX', 'LMT', 'EMR', 'ITW', 'DAL', 'NSC', 'RTX', 'DE']
[15, 15]
Counter({'HON': 2, 'MMM': 2, 'UTX': 2, 'CAT': 2, 'BA': 2, 'UNP': 2, 'GE': 2, 'FDX': 2, 'EMR': 2, 'LMT': 2, 'RTX': 2, 'ITW': 2, 'UPS': 1, 'GD': 1, 'NOC': 1, 'DAL': 1, 'NSC': 1, 'DE': 1})
['HON', 'UTX', 'CAT', 'MMM', 'GE', 'BA', 'UNP', 'FDX', 'UPS', 'RTX', 'DE', 'EMR', 'LMT', 'NOC', 'DHR']
[15, 15, 15]
Counter({'HON': 3, 'MMM': 3, 'UTX': 3, 'CAT': 3, 'BA': 3, 'UNP': 3, 'GE': 3, 'FDX': 3, 'EMR': 3, 'LMT': 3, 'RTX': 3, 'UPS': 2, 'ITW': 2, 'NOC': 2, 'DE': 2, 'GD': 1, 'DAL': 1, 'NSC': 1, 'DHR': 1})
The valid most common stocks are:  ['HON', 'MMM', 'UTX', 'CAT', 'BA', 'UNP', 'GE', 'FDX', 'EMR', 'LMT', 'RTX', 'UPS', 'ITW', 'NOC', 'DE']

In [49]:
industrials_stocks = list(pd.read_csv('sectors_new/stocks15_auto_S&P 500-20 industrials.csv')['Stocks'].T)
industrials_stocks

['HON',
 'MMM',
 'UTX',
 'CAT',
 'BA',
 'UNP',
 'GE',
 'FDX',
 'EMR',
 'LMT',
 'RTX',
 'UPS',
 'GD',
 'ITW',
 'NOC',
 'DAL',
 'NSC',
 'DE',
 'DHR']

In [50]:
check_if_stock_in_sp500(industrials_stocks)

HON in SP500
MMM in SP500
UTX NOT in SP500
CAT in SP500
BA in SP500
UNP in SP500
GE in SP500
FDX in SP500
EMR in SP500
LMT in SP500
RTX in SP500
UPS in SP500
GD in SP500
ITW in SP500
NOC in SP500
DAL in SP500
NSC in SP500
DE in SP500
DHR in SP500

## Consumer discretionary sector

In [51]:
generate_stocks_by_sector('S&P 500-25 consumer discretionary', 3, 15)

['AMZN', 'DIS', 'NKE', 'HD', 'MCD', 'SBUX', 'BKNG', 'TGT', 'LOW', 'CMCSA', 'GM', 'NFLX', 'BBY', 'TJX', 'EBAY']
[15]
Counter({'AMZN': 1, 'DIS': 1, 'NKE': 1, 'HD': 1, 'MCD': 1, 'SBUX': 1, 'BKNG': 1, 'TGT': 1, 'LOW': 1, 'CMCSA': 1, 'GM': 1, 'NFLX': 1, 'BBY': 1, 'TJX': 1, 'EBAY': 1})
['AMZN', 'TSLA', 'NKE', 'HD', 'MCD', 'SBUX', 'DIS', 'TGT', 'LOW', 'BKNG', 'CMCSA', 'GM', 'EBAY', 'BBY', 'F']
[15, 15]
Counter({'AMZN': 2, 'DIS': 2, 'NKE': 2, 'HD': 2, 'MCD': 2, 'SBUX': 2, 'BKNG': 2, 'TGT': 2, 'LOW': 2, 'CMCSA': 2, 'GM': 2, 'BBY': 2, 'EBAY': 2, 'NFLX': 1, 'TJX': 1, 'TSLA': 1, 'F': 1})
['AMZN', 'TSLA', 'HD', 'NKE', 'MCD', 'SBUX', 'DIS', 'TGT', 'LOW', 'BKNG', 'CMCSA', 'GM', 'F', 'BBY', 'KSS']
[15, 15, 15]
Counter({'AMZN': 3, 'DIS': 3, 'NKE': 3, 'HD': 3, 'MCD': 3, 'SBUX': 3, 'BKNG': 3, 'TGT': 3, 'LOW': 3, 'CMCSA': 3, 'GM': 3, 'BBY': 3, 'EBAY': 2, 'TSLA': 2, 'F': 2, 'NFLX': 1, 'TJX': 1, 'KSS': 1})
The valid most common stocks are:  ['AMZN', 'DIS', 'NKE', 'HD', 'MCD', 'SBUX', 'BKNG', 'TGT', 'LOW', 'CMCSA', 'GM', 'BBY', 'EBAY', 'TSLA', 'F']

In [56]:
consumer_discretionary_stocks = list(pd.read_csv('sectors_new/stocks15_auto_S&P 500-25 consumer discretionary.csv')['Stocks'].T)
consumer_discretionary_stocks

['AMZN',
 'DIS',
 'NKE',
 'HD',
 'MCD',
 'SBUX',
 'BKNG',
 'TGT',
 'LOW',
 'CMCSA',
 'GM',
 'NFLX',
 'BBY',
 'TJX',
 'EBAY',
 'TSLA',
 'F',
 'KSS']

In [57]:
check_if_stock_in_sp500(consumer_discretionary_stocks)

AMZN in SP500
DIS in SP500
NKE in SP500
HD in SP500
MCD in SP500
SBUX in SP500
BKNG in SP500
TGT in SP500
LOW in SP500
CMCSA in SP500
GM in SP500
NFLX in SP500
BBY in SP500
TJX in SP500
EBAY in SP500
TSLA in SP500
F in SP500
KSS NOT in SP500

## Consumer staples sector

In [55]:
generate_stocks_by_sector('S&P 500-30 consumer staples', 3, 15)

['PG', 'KO', 'PEP', 'WMT', 'CL', 'KMB', 'COST', 'PM', 'MO', 'MDLZ', 'CLX', 'MKC', 'GIS', 'EL', 'HSY']
[15]
Counter({'PG': 1, 'KO': 1, 'PEP': 1, 'WMT': 1, 'CL': 1, 'KMB': 1, 'COST': 1, 'PM': 1, 'MO': 1, 'MDLZ': 1, 'CLX': 1, 'MKC': 1, 'GIS': 1, 'EL': 1, 'HSY': 1})
['PG', 'KO', 'PEP', 'WMT', 'COST', 'CL', 'KMB', 'CLX', 'EL', 'GIS', 'K', 'HSY', 'MDLZ', 'MKC', 'SYY']
[15, 15]
Counter({'PG': 2, 'KO': 2, 'PEP': 2, 'WMT': 2, 'CL': 2, 'KMB': 2, 'COST': 2, 'MDLZ': 2, 'CLX': 2, 'MKC': 2, 'GIS': 2, 'EL': 2, 'HSY': 2, 'PM': 1, 'MO': 1, 'K': 1, 'SYY': 1})
['PG', 'KO', 'PEP', 'WMT', 'COST', 'CL', 'KMB', 'MDLZ', 'GIS', 'CLX', 'EL', 'MKC', 'HSY', 'ADM', 'SYY']
[15, 15, 15]
Counter({'PG': 3, 'KO': 3, 'PEP': 3, 'WMT': 3, 'CL': 3, 'KMB': 3, 'COST': 3, 'MDLZ': 3, 'CLX': 3, 'MKC': 3, 'GIS': 3, 'EL': 3, 'HSY': 3, 'SYY': 2, 'PM': 1, 'MO': 1, 'K': 1, 'ADM': 1})
The valid most common stocks are:  ['PG', 'KO', 'PEP', 'WMT', 'CL', 'KMB', 'COST', 'MDLZ', 'CLX', 'MKC', 'GIS', 'EL', 'HSY', 'SYY', 'PM']

In [58]:
consumer_staples_stocks = list(pd.read_csv('sectors_new/stocks15_auto_S&P 500-30 consumer staples.csv')['Stocks'].T)
check_if_stock_in_sp500(consumer_staples_stocks)

PG in SP500
KO in SP500
PEP in SP500
WMT in SP500
CL in SP500
KMB in SP500
COST in SP500
PM in SP500
MO in SP500
MDLZ in SP500
CLX in SP500
MKC in SP500
GIS in SP500
EL in SP500
HSY in SP500
K in SP500
SYY in SP500
ADM in SP500

## Health care sector

In [60]:
generate_stocks_by_sector('S&P 500-35 health care', 3, 15)

['JNJ', 'PFE', 'MRK', 'AMGN', 'ABBV', 'BMY', 'LLY', 'GILD', 'TMO', 'UNH', 'MDT', 'ABT', 'VRTX', 'REGN', 'ZTS']
[15]
Counter({'JNJ': 1, 'PFE': 1, 'MRK': 1, 'AMGN': 1, 'ABBV': 1, 'BMY': 1, 'LLY': 1, 'GILD': 1, 'TMO': 1, 'UNH': 1, 'MDT': 1, 'ABT': 1, 'VRTX': 1, 'REGN': 1, 'ZTS': 1})
['JNJ', 'PFE', 'MRK', 'ABT', 'AMGN', 'BMY', 'LLY', 'GILD', 'MDT', 'TMO', 'UNH', 'VRTX', 'BSX', 'ALXN', 'CI']
[15, 15]
Counter({'JNJ': 2, 'PFE': 2, 'MRK': 2, 'AMGN': 2, 'BMY': 2, 'LLY': 2, 'GILD': 2, 'TMO': 2, 'UNH': 2, 'MDT': 2, 'ABT': 2, 'VRTX': 2, 'ABBV': 1, 'REGN': 1, 'ZTS': 1, 'BSX': 1, 'ALXN': 1, 'CI': 1})
['JNJ', 'PFE', 'MRK', 'ABT', 'AMGN', 'BMY', 'GILD', 'LLY', 'TMO', 'MDT', 'UNH', 'DHR', 'ABBV', 'VRTX', 'REGN']
[15, 15, 15]
Counter({'JNJ': 3, 'PFE': 3, 'MRK': 3, 'AMGN': 3, 'BMY': 3, 'LLY': 3, 'GILD': 3, 'TMO': 3, 'UNH': 3, 'MDT': 3, 'ABT': 3, 'VRTX': 3, 'ABBV': 2, 'REGN': 2, 'ZTS': 1, 'BSX': 1, 'ALXN': 1, 'CI': 1, 'DHR': 1})
The valid most common stocks are:  ['JNJ', 'PFE', 'MRK', 'AMGN', 'BMY', 'LLY', 'GILD', 'TMO', 'UNH', 'MDT', 'ABT', 'VRTX', 'ABBV', 'REGN', 'ZTS']

In [61]:
health_care_stocks = list(pd.read_csv('sectors_new/stocks15_auto_S&P 500-35 health care.csv')['Stocks'].T)
check_if_stock_in_sp500(health_care_stocks)

JNJ in SP500
PFE in SP500
MRK in SP500
AMGN in SP500
ABBV in SP500
BMY in SP500
LLY in SP500
GILD in SP500
TMO in SP500
UNH in SP500
MDT in SP500
ABT in SP500
VRTX in SP500
REGN in SP500
ZTS in SP500
BSX in SP500
ALXN NOT in SP500
CI in SP500
DHR in SP500

## Financials sector

In [63]:
generate_stocks_by_sector('S&P 500-40 financials', 3, 15)

['JPM', 'BAC', 'WFC', 'C', 'GS', 'MS', 'AXP', 'V', 'MA', 'SCHW', 'COF', 'SPGI', 'BLK', 'BK', 'STT']
[15]
Counter({'JPM': 1, 'BAC': 1, 'WFC': 1, 'C': 1, 'GS': 1, 'MS': 1, 'AXP': 1, 'V': 1, 'MA': 1, 'SCHW': 1, 'COF': 1, 'SPGI': 1, 'BLK': 1, 'BK': 1, 'STT': 1})
['JPM', 'BAC', 'C', 'WFC', 'GS', 'MS', 'AXP', 'V', 'MA', 'SCHW', 'BLK', 'SPGI', 'CME', 'ICE', 'STT']
[15, 15]
Counter({'JPM': 2, 'BAC': 2, 'WFC': 2, 'C': 2, 'GS': 2, 'MS': 2, 'AXP': 2, 'V': 2, 'MA': 2, 'SCHW': 2, 'SPGI': 2, 'BLK': 2, 'STT': 2, 'COF': 1, 'BK': 1, 'CME': 1, 'ICE': 1})
['JPM', 'BAC', 'WFC', 'C', 'GS', 'MS', 'AXP', 'V', 'MA', 'BLK', 'SCHW', 'PNC', 'COF', 'SYF', 'DFS']
[15, 15, 15]
Counter({'JPM': 3, 'BAC': 3, 'WFC': 3, 'C': 3, 'GS': 3, 'MS': 3, 'AXP': 3, 'V': 3, 'MA': 3, 'SCHW': 3, 'BLK': 3, 'COF': 2, 'SPGI': 2, 'STT': 2, 'BK': 1, 'CME': 1, 'ICE': 1, 'PNC': 1, 'SYF': 1, 'DFS': 1})
The valid most common stocks are:  ['JPM', 'BAC', 'WFC', 'C', 'GS', 'MS', 'AXP', 'V', 'MA', 'SCHW', 'BLK', 'COF', 'SPGI', 'STT', 'BK']

In [64]:
financials_stocks = list(pd.read_csv('sectors_new/stocks15_auto_S&P 500-40 financials.csv')['Stocks'].T)
check_if_stock_in_sp500(financials_stocks)

JPM in SP500
BAC in SP500
WFC in SP500
C in SP500
GS in SP500
MS in SP500
AXP in SP500
V in SP500
MA in SP500
SCHW in SP500
COF in SP500
SPGI in SP500
BLK in SP500
BK in SP500
STT in SP500
CME in SP500
ICE in SP500
PNC in SP500
SYF in SP500
DFS in SP500

## Informational technology sector

In [65]:
generate_stocks_by_sector('S&P 500-45 informational technology', 3, 15)

['AAPL', 'MSFT', 'AMZN', 'GOOGL', 'META', 'V', 'MA', 'ADBE', 'CRM', 'INTC', 'NVDA', 'TXN', 'CSCO', 'AVGO', 'AMAT']
[15]
Counter({'AAPL': 1, 'MSFT': 1, 'AMZN': 1, 'GOOGL': 1, 'META': 1, 'V': 1, 'MA': 1, 'ADBE': 1, 'CRM': 1, 'INTC': 1, 'NVDA': 1, 'TXN': 1, 'CSCO': 1, 'AVGO': 1, 'AMAT': 1})
['AAPL', 'MSFT', 'AMZN', 'GOOGL', 'META', 'INTC', 'NVDA', 'ADBE', 'CRM', 'PYPL', 'AMD', 'CSCO', 'ORCL', 'IBM', 'TXN']
[15, 15]
Counter({'AAPL': 2, 'MSFT': 2, 'AMZN': 2, 'GOOGL': 2, 'META': 2, 'ADBE': 2, 'CRM': 2, 'INTC': 2, 'NVDA': 2, 'TXN': 2, 'CSCO': 2, 'V': 1, 'MA': 1, 'AVGO': 1, 'AMAT': 1, 'PYPL': 1, 'AMD': 1, 'ORCL': 1, 'IBM': 1})
['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META', 'NVDA', 'INTC', 'ADBE', 'CSCO', 'CRM', 'PYPL', 'IBM', 'AMD', 'AVGO', 'ORCL']
[15, 15, 15]
Counter({'AAPL': 3, 'MSFT': 3, 'AMZN': 3, 'GOOGL': 3, 'META': 3, 'ADBE': 3, 'CRM': 3, 'INTC': 3, 'NVDA': 3, 'CSCO': 3, 'TXN': 2, 'AVGO': 2, 'PYPL': 2, 'AMD': 2, 'ORCL': 2, 'IBM': 2, 'V': 1, 'MA': 1, 'AMAT': 1})
The valid most common stocks are:  ['AAPL', 'MSFT', 'AMZN', 'GOOGL', 'META', 'ADBE', 'CRM', 'INTC', 'NVDA', 'CSCO', 'TXN', 'AVGO', 'PYPL', 'AMD', 'ORCL']

In [66]:
informational_technology_stocks = list(pd.read_csv('sectors_new/stocks15_auto_S&P 500-45 informational technology.csv')['Stocks'].T)
check_if_stock_in_sp500(informational_technology_stocks)

AAPL in SP500
MSFT in SP500
AMZN in SP500
GOOGL in SP500
META in SP500
V in SP500
MA in SP500
ADBE in SP500
CRM in SP500
INTC in SP500
NVDA in SP500
TXN in SP500
CSCO in SP500
AVGO in SP500
AMAT in SP500
PYPL in SP500
AMD in SP500
ORCL in SP500
IBM in SP500

## Communication services sector

In [67]:
generate_stocks_by_sector('S&P 500-50 communication services', 3, 15)

['GOOGL', 'META', 'CMCSA', 'VZ', 'T', 'NFLX', 'DIS', 'CHTR', 'TWTR', 'ATVI', 'EA', 'VIAC', 'SNAP', 'SPOT', 'DISCA']
[15]
Counter({'GOOGL': 1, 'META': 1, 'CMCSA': 1, 'VZ': 1, 'T': 1, 'NFLX': 1, 'DIS': 1, 'CHTR': 1, 'TWTR': 1, 'ATVI': 1, 'EA': 1, 'VIAC': 1, 'SNAP': 1, 'SPOT': 1, 'DISCA': 1})
['GOOGL', 'META', 'NFLX', 'VZ', 'T', 'CMCSA', 'DIS', 'CHTR', 'TWTR', 'SNAP', 'ATVI', 'EA', 'SPOT', 'VIAC', 'DISCA']
[15, 15]
Counter({'GOOGL': 2, 'META': 2, 'CMCSA': 2, 'VZ': 2, 'T': 2, 'NFLX': 2, 'DIS': 2, 'CHTR': 2, 'TWTR': 2, 'ATVI': 2, 'EA': 2, 'VIAC': 2, 'SNAP': 2, 'SPOT': 2, 'DISCA': 2})
['GOOGL', 'META', 'NFLX', 'VZ', 'T', 'CMCSA', 'CHTR', 'DIS', 'TWTR', 'ATVI', 'EA', 'SPOT', 'MTCH', 'VIAC', 'SIRI']
[15, 15, 15]
Counter({'GOOGL': 3, 'META': 3, 'CMCSA': 3, 'VZ': 3, 'T': 3, 'NFLX': 3, 'DIS': 3, 'CHTR': 3, 'TWTR': 3, 'ATVI': 3, 'EA': 3, 'VIAC': 3, 'SPOT': 3, 'SNAP': 2, 'DISCA': 2, 'MTCH': 1, 'SIRI': 1})
The valid most common stocks are:  ['GOOGL', 'META', 'CMCSA', 'VZ', 'T', 'NFLX', 'DIS', 'CHTR', 'TWTR', 'ATVI', 'EA', 'VIAC', 'SPOT', 'SNAP', 'DISCA']

In [68]:
communication_services_stocks = list(pd.read_csv('sectors_new/stocks15_auto_S&P 500-50 communication services.csv')['Stocks'].T)
check_if_stock_in_sp500(communication_services_stocks)

GOOGL in SP500
META in SP500
CMCSA in SP500
VZ in SP500
T in SP500
NFLX in SP500
DIS in SP500
CHTR in SP500
TWTR NOT in SP500
ATVI NOT in SP500
EA in SP500
VIAC NOT in SP500
SNAP NOT in SP500
SPOT NOT in SP500
DISCA NOT in SP500
MTCH in SP500
SIRI NOT in SP500

## Utilities sector

In [69]:
generate_stocks_by_sector('S&P 500-55 utilities', 3, 15)

['NEE', 'DUK', 'D', 'SO', 'AEP', 'EXC', 'XEL', 'ED', 'PEG', 'WEC', 'CMS', 'ES', 'FE', 'ETR', 'PPL']
[15]
Counter({'NEE': 1, 'DUK': 1, 'D': 1, 'SO': 1, 'AEP': 1, 'EXC': 1, 'XEL': 1, 'ED': 1, 'PEG': 1, 'WEC': 1, 'CMS': 1, 'ES': 1, 'FE': 1, 'ETR': 1, 'PPL': 1})
['NEE', 'D', 'DUK', 'AEP', 'SO', 'EXC', 'ED', 'PEG', 'XEL', 'SRE', 'WEC', 'ES', 'FE', 'CMS', 'PPL']
[15, 15]
Counter({'NEE': 2, 'DUK': 2, 'D': 2, 'SO': 2, 'AEP': 2, 'EXC': 2, 'XEL': 2, 'ED': 2, 'PEG': 2, 'WEC': 2, 'CMS': 2, 'ES': 2, 'FE': 2, 'PPL': 2, 'ETR': 1, 'SRE': 1})
['NEE', 'D', 'DUK', 'SO', 'AEP', 'EXC', 'ED', 'PEG', 'SRE', 'EIX', 'XEL', 'WEC', 'PPL', 'ES', 'CMS']
[15, 15, 15]
Counter({'NEE': 3, 'DUK': 3, 'D': 3, 'SO': 3, 'AEP': 3, 'EXC': 3, 'XEL': 3, 'ED': 3, 'PEG': 3, 'WEC': 3, 'CMS': 3, 'ES': 3, 'PPL': 3, 'FE': 2, 'SRE': 2, 'ETR': 1, 'EIX': 1})
The valid most common stocks are:  ['NEE', 'DUK', 'D', 'SO', 'AEP', 'EXC', 'XEL', 'ED', 'PEG', 'WEC', 'CMS', 'ES', 'PPL', 'FE', 'SRE']

In [70]:
utilities_stocks = list(pd.read_csv('sectors_new/stocks15_auto_S&P 500-55 utilities.csv')['Stocks'].T)
check_if_stock_in_sp500(utilities_stocks)

NEE in SP500
DUK in SP500
D in SP500
SO in SP500
AEP in SP500
EXC in SP500
XEL in SP500
ED in SP500
PEG in SP500
WEC in SP500
CMS in SP500
ES in SP500
FE in SP500
ETR in SP500
PPL in SP500
SRE in SP500
EIX in SP500

## Real estate sector

In [71]:
generate_stocks_by_sector('S&P 500-60 real estate', 3, 15)

['AMT', 'PLD', 'SPG', 'EQIX', 'PSA', 'DLR', 'AVB', 'WELL', 'VTR', 'O', 'BXP', 'ARE', 'ESS', 'VNO', 'EXR']
[15]
Counter({'AMT': 1, 'PLD': 1, 'SPG': 1, 'EQIX': 1, 'PSA': 1, 'DLR': 1, 'AVB': 1, 'WELL': 1, 'VTR': 1, 'O': 1, 'BXP': 1, 'ARE': 1, 'ESS': 1, 'VNO': 1, 'EXR': 1})
['AMT', 'PLD', 'SPG', 'EQIX', 'PSA', 'DLR', 'AVB', 'WELL', 'O', 'VTR', 'BXP', 'ARE', 'EXR', 'ESS', 'FRT']
[15, 15]
Counter({'AMT': 2, 'PLD': 2, 'SPG': 2, 'EQIX': 2, 'PSA': 2, 'DLR': 2, 'AVB': 2, 'WELL': 2, 'VTR': 2, 'O': 2, 'BXP': 2, 'ARE': 2, 'ESS': 2, 'EXR': 2, 'VNO': 1, 'FRT': 1})
['AMT', 'PLD', 'EQIX', 'DLR', 'SPG', 'CCI', 'PSA', 'AVB', 'WELL', 'VTR', 'O', 'ARE', 'ESS', 'BXP', 'EXR']
[15, 15, 15]
Counter({'AMT': 3, 'PLD': 3, 'SPG': 3, 'EQIX': 3, 'PSA': 3, 'DLR': 3, 'AVB': 3, 'WELL': 3, 'VTR': 3, 'O': 3, 'BXP': 3, 'ARE': 3, 'ESS': 3, 'EXR': 3, 'VNO': 1, 'FRT': 1, 'CCI': 1})
The valid most common stocks are:  ['AMT', 'PLD', 'SPG', 'EQIX', 'PSA', 'DLR', 'AVB', 'WELL', 'VTR', 'O', 'BXP', 'ARE', 'ESS', 'EXR', 'VNO']

In [72]:
real_estate_stocks = list(pd.read_csv('sectors_new/stocks15_auto_S&P 500-60 real estate.csv')['Stocks'].T)
check_if_stock_in_sp500(real_estate_stocks)

AMT in SP500
PLD in SP500
SPG in SP500
EQIX in SP500
PSA in SP500
DLR in SP500
AVB in SP500
WELL in SP500
VTR in SP500
O in SP500
BXP in SP500
ARE in SP500
ESS in SP500
VNO NOT in SP500
EXR in SP500
FRT in SP500
CCI in SP500

## Forming 11 sector potfolios via splitting the SP500 assets by sector

In [76]:
df_sp500

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
499,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
500,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
501,ZION,Zions Bancorporation,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [75]:
df_sp500['GICS Sector'].unique()

array(['Industrials', 'Health Care', 'Information Technology',
       'Consumer Staples', 'Utilities', 'Financials',
       'Consumer Discretionary', 'Materials', 'Real Estate',
       'Communication Services', 'Energy'], dtype=object)

In [78]:
sp500_industrials_stocks = list(df_sp500[df_sp500['GICS Sector'] == 'Industrials']['Symbol'])
len(sp500_industrials_stocks)

77

In [79]:
sp500_health_care_stocks = list(df_sp500[df_sp500['GICS Sector'] == 'Health Care']['Symbol'])
len(sp500_health_care_stocks)

64

In [80]:
sp500_informational_technology_stocks = list(df_sp500[df_sp500['GICS Sector'] == 'Information Technology']['Symbol'])
len(sp500_informational_technology_stocks)

64

In [81]:
sp500_consumer_staples_stocks = list(df_sp500[df_sp500['GICS Sector'] == 'Consumer Staples']['Symbol'])
len(sp500_consumer_staples_stocks)

38

In [82]:
sp500_utilities_stocks = list(df_sp500[df_sp500['GICS Sector'] == 'Utilities']['Symbol'])
len(sp500_utilities_stocks)

30

In [83]:
sp500_financials_stocks = list(df_sp500[df_sp500['GICS Sector'] == 'Financials']['Symbol'])
len(sp500_financials_stocks)

72

In [84]:
sp500_consumer_discretionary_stocks = list(df_sp500[df_sp500['GICS Sector'] == 'Consumer Discretionary']['Symbol'])
len(sp500_consumer_discretionary_stocks)

53

In [85]:
sp500_materials_stocks = list(df_sp500[df_sp500['GICS Sector'] == 'Materials']['Symbol'])
len(sp500_materials_stocks)

29

In [86]:
sp500_real_estate_stocks = list(df_sp500[df_sp500['GICS Sector'] == 'Real Estate']['Symbol'])
len(sp500_real_estate_stocks)

31

In [87]:
sp500_communication_services_stocks = list(df_sp500[df_sp500['GICS Sector'] == 'Communication Services']['Symbol'])
len(sp500_communication_services_stocks)

22

In [88]:
sp500_energy_stocks = list(df_sp500[df_sp500['GICS Sector'] == 'Energy']['Symbol'])
len(sp500_energy_stocks)

23

In [102]:
np.array(sp500_energy_stocks)

array(['APA', 'BKR', 'CVX', 'COP', 'CTRA', 'DVN', 'FANG', 'EOG', 'EQT',
       'XOM', 'HAL', 'HES', 'KMI', 'MRO', 'MPC', 'OXY', 'OKE', 'PSX',
       'PXD', 'SLB', 'TRGP', 'VLO', 'WMB'], dtype='<U4')

## Get weights for ChatGPT portfolios

In [97]:
sectors = ['S&P 500-10 energy', 'S&P 500-15 materials', 'S&P 500-20 industrials',  'S&P 500-25 consumer discretionary',\
            'S&P 500-30 consumer staples', 'S&P 500-35 health care', 'S&P 500-40 financials', 'S&P 500-45 informational technology', \
                'S&P 500-50 communication services', 'S&P 500-55 utilities', 'S&P 500-60 real estate']

In [89]:
def convert_reponse4_to_df(coutput4):
    df = pd.DataFrame()

    # Split the input string into pairs of stock and weight
    pairs = coutput4.split(',')

    # Create lists to store stock and weight values
    stocks = []
    weights = []

    # stock_pattern = r"'?([A-Z\-]+)'"

    # Extract stock and weight values from pairs
    for pair in pairs:
        stock, weight = pair.split(':')

    # if stock_pattern.fullmatch(stock):
        stocks.append(stock)
        weights.append(float(weight))

    # Create a DataFrame
    df = pd.DataFrame({'Stock': stocks, 'Weight': weights})

    if not np.isclose(df['Weight'].sum(), 1):
        df['Weight'] = df['Weight'] / df['Weight'].sum()

    return df

In [94]:
def get_weights_by_sector(index):
    csv_path_read = f'sectors_new/stocks15_auto_{index}.csv'
    sector_df = pd.read_csv(csv_path_read)

    temp_df = sector_df[sector_df['IsValid'] == 1]
    input = temp_df['Stocks'].to_list()
    print(input)
    prompt3 = f"Assume you're designing a theoretical model portfolio from these S&P 500 stocks: {input}. Provide a hypothetical example of how you might distribute the weightage of these stocks (normalized i.e weights should add up to 1.00) in the portfolio to potentially outperform the S&P 500 index. Also mention the underlying strategy or logic which you used to assign these weights"
    prompt3


    csv_path = f'weights_response_new/responses15_auto_{index}.csv'
    # Check if CSV file exists
    if os.path.isfile(csv_path):
        # Read from CSV
        print("Reading from local csv file")
        df = pd.read_csv(csv_path)

        # Assign responses
        coutput3 = df.loc[df['ResponseID'] == 'coutput3', 'Response'].values[0]
        print(coutput3)

    else:
        # Call OpenAI API for the third response
        response3 = openai.ChatCompletion.create(
            model=model,
            messages=[
            {"role": "system", "content": "You are a helpful assistant. Your task is to create a hypothetical allocation of weights to the stocks in a theoretical investment fund."},
            {"role": "user", "content": prompt3},
            ],
            max_tokens=max_tokens,
            n=n,
            stop=stop,
            temperature=temperature,
        )

        coutput3 = response3['choices'][0]['message']['content']
        with open(csv_path, 'w', encoding='utf-8') as f:
            f.write(coutput3)
        # print(coutput3)


    prompt4 = f'Extract tickers of stocks and corresponding weights as a single comma "," separated string, with the weights expressed as floats : "{coutput3}". Provide a list of type TICKER: weight, no extra symbols used.'


    csv_path = f'weights_assigned_new/responses15_auto_{index}.csv'
    # Check if CSV file exists
    if os.path.isfile(csv_path):
        # Read from CSV
        print("Reading from local csv file")
        df = pd.read_csv(csv_path)

        # Assign responses
        coutput4 = df.loc[df['ResponseID'] == 'coutput4', 'Response'].values[0]
        print(coutput4)

    else:
        print(f'calling openai for response to prompt 4 sector {index}')
        # Call OpenAI API for the fourth response
        response4 = openai.ChatCompletion.create(
            model=model,
            messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt4},
            ],
            max_tokens=max_tokens,
            n=n,
            stop=stop,
            temperature=temperature,
        )

        coutput4 = response4['choices'][0]['message']['content']
        print(coutput4.strip('"'))

        weights_df = convert_reponse4_to_df(coutput4)

        # Save to CSV
        weights_df.to_csv(csv_path, index=False)

    return coutput4

In [98]:
for sector in sectors:
    get_weights_by_sector(sector)

['AAPL', 'MSFT', 'AMZN', 'GOOGL', 'META', 'ADBE', 'CRM', 'INTC', 'NVDA', 'TXN', 'CSCO', 'AVGO', 'PYPL', 'AMD', 'ORCL']
calling openai for response to prompt 4 sector S&P 500-45 informational technology
AAPL: 0.15, MSFT: 0.15, AMZN: 0.12, GOOGL: 0.12, META: 0.10, ADBE: 0.08, CRM: 0.07, INTC: 0.05, NVDA: 0.05, TXN: 0.04, CSCO: 0.03, AVGO: 0.03, PYPL: 0.02, AMD: 0.01, ORCL: 0.01
['GOOGL', 'META', 'CMCSA', 'VZ', 'T', 'NFLX', 'DIS', 'CHTR', 'TWTR', 'ATVI', 'EA', 'VIAC', 'SNAP', 'SPOT', 'DISCA']
calling openai for response to prompt 4 sector S&P 500-50 communication services
GOOGL: 15, META: 10, CMCSA: 8, VZ: 7, T: 6, NFLX: 12, DIS: 10, CHTR: 5, TWTR: 4, ATVI: 6, EA: 5, VIAC: 5, SNAP: 4, SPOT: 3, DISCA: 5
['NEE', 'DUK', 'D', 'SO', 'AEP', 'EXC', 'XEL', 'ED', 'PEG', 'WEC', 'CMS', 'ES', 'FE', 'PPL', 'SRE']
calling openai for response to prompt 4 sector S&P 500-55 utilities
NEE: 0.15, DUK: 0.10, D: 0.08, SO: 0.07, AEP: 0.06, EXC: 0.05, XEL: 0.05, ED: 0.05, PEG: 0.07, WEC: 0.06, CMS: 0.04, ES: 0.04, FE: 0.04, PPL: 0.04, SRE: 0.10
['AMT', 'PLD', 'SPG', 'EQIX', 'PSA', 'DLR', 'AVB', 'WELL', 'VTR', 'O', 'BXP', 'ARE', 'ESS', 'VNO', 'EXR']
calling openai for response to prompt 4 sector S&P 500-60 real estate
AMT: 0.10, PLD: 0.10, SPG: 0.08, EQIX: 0.08, PSA: 0.08, DLR: 0.08, AVB: 0.07, WELL: 0.07, VTR: 0.06, O: 0.06, BXP: 0.05, ARE: 0.05, ESS: 0.05, VNO: 0.04, EXR: 0.03

## Compose equally weighted sector portfolios

In [103]:
sectors

['S&P 500-10 energy',
 'S&P 500-15 materials',
 'S&P 500-20 industrials',
 'S&P 500-25 consumer discretionary',
 'S&P 500-30 consumer staples',
 'S&P 500-35 health care',
 'S&P 500-40 financials',
 'S&P 500-45 informational technology',
 'S&P 500-50 communication services',
 'S&P 500-55 utilities',
 'S&P 500-60 real estate']

In [105]:
sp500_stocks_list = [sp500_energy_stocks, sp500_materials_stocks, sp500_industrials_stocks, sp500_consumer_discretionary_stocks,\
                    sp500_consumer_staples_stocks, sp500_health_care_stocks, sp500_financials_stocks,\
                        sp500_informational_technology_stocks, sp500_communication_services_stocks,\
                        sp500_utilities_stocks, sp500_real_estate_stocks]

In [106]:
for sector, stocks_list in zip(sectors, sp500_stocks_list):
    n = len(stocks_list)
    weights_list = [1/n for _ in range(n)]

    csv_path_write = f'weights_sector_equal/stocks15_auto_{sector}.csv'

    temp_df = pd.DataFrame({'Stock': stocks_list, 'Weight': weights_list})

    if not np.isclose(temp_df['Weight'].sum(), 1):
        temp_df['Weight'] = temp_df['Weight'] / temp_df['Weight'].sum()

    temp_df.to_csv(csv_path_write)

## Comparing each of 11 portfolios performance

In [107]:
def process_sector_data(df_sector):
    # Remove spaces from stock names
    stocks = list(df_sector['Stock'].str.replace(" ", "").values)

    # Calculate equal weights
    eq_weights = [1/len(stocks)] * len(stocks)

    # Get GPT weights
    gpt_weights = list(df_sector['Weight'].values.astype(float))

    return stocks, eq_weights, gpt_weights

In [117]:
sector_names = ['energy', 'materials', 'industrials', 'consumer_discretionary', 'consumer_staples',\
                'health_care', 'financials', 'informational_technology', 'communication_services',\
                'utilities', 'real_estate']

In [119]:
for sector, name in zip(sectors, sector_names):
    # Assuming CSV files are named like 'responses15_auto_SectorName.csv'
    csv_filename = f'weights_assigned_new/responses15_auto_{sector}.csv'
    
    df_sector = pd.read_csv(csv_filename)
    
    stocks, eq_weights, gpt_weights = process_sector_data(df_sector)
    
    # Assign variables dynamically
    globals()[f'df_{name}'] = df_sector
    globals()[f'stocks_{name}'] = stocks
    globals()[f'eq_weights_{name}'] = eq_weights
    globals()[f'weights_gpt_{name}'] = gpt_weights

In [120]:
weights_gpt_energy

[0.1041666666666666,
 0.0833333333333333,
 0.0624999999999999,
 0.0520833333333333,
 0.0729166666666666,
 0.0937499999999999,
 0.0624999999999999,
 0.0520833333333333,
 0.0729166666666666,
 0.0624999999999999,
 0.0520833333333333,
 0.0624999999999999,
 0.0520833333333333,
 0.0729166666666666,
 0.0416666666666666]